// Kendi yazdığım örnek cümleler - kelimeye göre eşleşir (küçük harf).
// Henüz her kelime için cümle yok; zamanla genişletilecek.
const EXAMPLES = {
  "a/an": "I saw a cat in the garden.",
  "about": "This book is about space.",
  "above": "The plane flew above the clouds.",
  "across": "She walked across the street.",
  "action": "The movie is full of action.",
  "add": "Please add your name to the list.",
  "address": "Can you tell me your address?",
  "afraid": "I am not afraid of the dark.",
  "after": "We ate dinner after the movie.",
  "afternoon": "I have a meeting this afternoon.",
  "again": "Can you say that again, please?",
  "age": "What is your age?",
  "ago": "I met her two years ago.",
  "agree": "I agree with your idea.",
  "air": "The air is fresh in the mountains.",
  "airport": "We arrived at the airport early.",
  "all": "All my friends came to the party.",
  "always": "She always drinks tea in the morning.",
  "animal": "My favourite animal is the elephant.",
  "answer": "I don't know the answer to this question.",
  "apple": "He ate a red apple for lunch.",
  "arm": "She hurt her arm playing tennis.",
  "arrive": "The train will arrive at six o'clock.",
  "ask": "You can ask me anything.",
  "aunt": "My aunt lives in another city.",
  "baby": "The baby is sleeping now.",
  "back": "He went back home after work.",
  "bad": "The weather was really bad yesterday.",
  "bag": "I forgot my bag at the office.",
  "ball": "The children played with a ball.",
  "bank": "I need to go to the bank.",
  "be": "I want to be a doctor.",
  "beach": "We spent the day at the beach.",
  "beautiful": "The sunset was beautiful tonight.",
  "because": "I stayed home because it was raining.",
  "become": "She wants to become a teacher.",
  "bed": "I go to bed at eleven every night.",
  "before": "Please call me before you arrive.",
  "begin": "The class will begin in ten minutes.",
  "believe": "I believe you can do it.",
  "best": "This is the best coffee I've had.",
  "better": "I feel better today than yesterday.",
  "between": "The shop is between the bank and the cafe.",
  "big": "They live in a big house.",
  "bird": "A small bird landed on the window.",
  "birthday": "Today is my sister's birthday.",
  "black": "He was wearing a black jacket.",
  "boat": "We took a boat across the lake.",
  "body": "Exercise is good for your body.",
  "book": "I'm reading an interesting book.",
  "bored": "The children were bored on the long trip.",
  "boring": "The lecture was a bit boring.",
  "both": "Both of my parents are teachers.",
  "box": "There is a box under the table.",
  "boy": "The boy is playing in the park.",
  "bread": "We bought fresh bread this morning.",
  "break": "Let's take a short break.",
  "breakfast": "I usually have eggs for breakfast.",
  "bring": "Can you bring your notebook tomorrow?",
  "brother": "My brother works in a bank.",
  "build": "They are going to build a new school.",
  "bus": "I take the bus to work every day.",
  "business": "She started her own business last year.",
  "busy": "I'm too busy to talk right now.",
  "buy": "I need to buy some vegetables.",
  "call": "I'll call you tonight.",
  "car": "We travelled by car to the coast.",
  "carry": "Can you help me carry these bags?",
  "cat": "The cat is sleeping on the sofa.",
  "change": "Things can change very quickly.",
  "cheap": "This restaurant is cheap but delicious.",
  "check": "Please check your email.",
  "child": "Every child needs love and support.",
  "choose": "It's hard to choose between the two.",
  "city": "London is a very old city.",
  "clean": "She keeps her room very clean.",
  "close": "Please close the door.",
  "cold": "It's very cold outside today.",
  "come": "Can you come to my house tomorrow?",
  "cook": "My father loves to cook on weekends.",
  "cost": "How much does this shirt cost?",
  "country": "Turkey is a beautiful country.",
  "cry": "The baby started to cry.",
  "cut": "Be careful, the knife can cut you.",
  "dance": "They danced all night at the wedding.",
  "dangerous": "Driving too fast is dangerous.",
  "dark": "It gets dark early in winter.",
  "day": "It was a wonderful day.",
  "decide": "I can't decide what to eat.",
  "delicious": "This soup is absolutely delicious.",
  "describe": "Can you describe what happened?",
  "difficult": "The exam was more difficult than I expected.",
  "dinner": "We're having dinner at seven.",
  "dirty": "My shoes are dirty from the rain.",
  "do": "What do you do for a living?",
  "dog": "Their dog loves to run in the park.",
  "door": "Please close the door behind you.",
  "draw": "She likes to draw pictures of animals.",
  "dream": "I had a strange dream last night.",
  "drink": "Would you like something to drink?",
  "drive": "He drives to work every morning.",
  "early": "We woke up early to catch the flight.",
  "easy": "The test was easier than I thought.",
  "eat": "Let's eat before the movie starts.",
  "egg": "I had a boiled egg for breakfast.",
  "empty": "The bottle is completely empty.",
  "end": "The story has a happy end.",
  "enjoy": "I really enjoy reading in the evening.",
  "enough": "We don't have enough time.",
  "even": "Even my dad liked the movie.",
  "evening": "See you this evening.",
  "every": "I go running every morning.",
  "example": "Can you give me an example?",
  "excited": "The kids were excited about the trip.",
  "expensive": "That watch looks quite expensive.",
  "explain": "Could you explain this again?",
  "eye": "She has beautiful green eyes.",
  "face": "He had a smile on his face.",
  "family": "I spent the weekend with my family.",
  "famous": "He became famous after that film.",
  "far": "The station is not far from here.",
  "fast": "He runs really fast.",
  "father": "My father taught me how to swim.",
  "favourite": "Pizza is my favourite food.",
  "feel": "I feel much better now.",
  "few": "There are only a few apples left.",
  "fight": "The two brothers had a fight.",
  "find": "I can't find my keys.",
  "finish": "We need to finish this today.",
  "fire": "They sat around the fire and talked.",
  "first": "This is my first time in Paris.",
  "fish": "We had fish for dinner.",
  "food": "The food at that restaurant is great.",
  "for": "This gift is for you.",
  "forget": "Please don't forget to call me.",
  "free": "Are you free this weekend?",
  "friend": "She is my best friend.",
  "from": "I'm from Turkey.",
  "full": "The bus was completely full.",
  "fun": "We had so much fun at the party.",
  "funny": "That joke was really funny.",
  "future": "I often think about the future.",
  "game": "Let's play a game.",
  "garden": "There are roses in our garden.",
  "get": "Can you get some milk from the shop?",
  "girl": "The girl is reading a book.",
  "give": "Can you give me your phone number?",
  "go": "Let's go for a walk.",
  "good": "This is a really good idea.",
  "great": "We had a great time yesterday.",
  "green": "She was wearing a green dress.",
  "group": "We worked in small groups.",
  "grow": "Children grow so fast.",
  "guess": "Can you guess what I bought?",
  "hair": "Her hair is very long.",
  "half": "I ate half of the cake.",
  "hand": "He raised his hand to answer.",
  "happen": "What happened yesterday?",
  "happy": "I'm so happy to see you.",
  "hard": "This question is really hard.",
  "hate": "I hate waiting in long queues.",
  "have": "Do you have a pen?",
  "he": "He is my classmate.",
  "hear": "Did you hear that noise?",
  "help": "Can you help me with this?",
  "here": "Come here, please.",
  "high": "The mountain is very high.",
  "history": "I love reading about history.",
  "hobby": "My hobby is painting.",
  "holiday": "We're going on holiday next week.",
  "home": "I'll be home by six.",
  "hope": "I hope you feel better soon.",
  "hot": "It's really hot today.",
  "house": "They bought a new house.",
  "how": "How are you today?",
  "hungry": "I'm really hungry, let's eat.",
  "idea": "That's a great idea.",
  "if": "If it rains, we'll stay home.",
  "imagine": "Imagine living on the moon.",
  "important": "Education is very important.",
  "in": "The keys are in my bag.",
  "interesting": "This is a very interesting story.",
  "job": "She got a new job last month.",
  "just": "I just finished my homework.",
  "keep": "You can keep the book.",
  "kind": "She's a very kind person.",
  "know": "I don't know his name.",
  "language": "She speaks three languages.",
  "large": "They live in a large apartment.",
  "last": "I saw him last week.",
  "late": "Sorry, I'm running a bit late.",
  "laugh": "We laughed all evening.",
  "learn": "I want to learn Spanish.",
  "leave": "The bus leaves at nine.",
  "life": "City life can be very busy.",
  "light": "Please turn on the light.",
  "like": "I like this song a lot.",
  "listen": "Listen to me carefully.",
  "little": "There's a little milk left.",
  "live": "They live near the sea.",
  "long": "It was a long journey.",
  "look": "Look at that beautiful view.",
  "lose": "I don't want to lose this game.",
  "love": "I love spending time with my family.",
  "lunch": "Let's have lunch together.",
  "make": "Can you make dinner tonight?",
  "man": "The man was reading a newspaper.",
  "many": "There are many reasons to visit Istanbul.",
  "meet": "Nice to meet you.",
  "milk": "I drink milk every morning.",
  "money": "I don't have much money with me.",
  "morning": "Good morning, how did you sleep?",
  "most": "Most people enjoy the summer.",
  "mother": "My mother is a nurse.",
  "move": "We're moving to a new house.",
  "much": "Thank you very much.",
  "music": "She listens to music every day.",
  "name": "What is your name?",
  "near": "The shop is near my house.",
  "need": "I need some help, please.",
  "never": "I have never been to Japan.",
  "new": "I bought a new phone.",
  "next": "See you next week.",
  "nice": "It was nice to meet you.",
  "night": "I couldn't sleep last night.",
  "now": "I have to go now.",
  "number": "Can I have your phone number?",
  "often": "I often walk to work.",
  "old": "This building is very old.",
  "open": "Please open the window.",
  "other": "I have other plans tonight.",
  "over": "The game is over.",
  "people": "There were many people at the concert.",
  "person": "She's a very kind person.",
  "place": "This is a beautiful place.",
  "play": "The kids like to play outside.",
  "please": "Close the door, please.",
  "problem": "We solved the problem together.",
  "question": "Can I ask you a question?",
  "quiet": "The library is always quiet.",
  "read": "I read a book every night.",
  "ready": "Are you ready to go?",
  "really": "I really like this song.",
  "remember": "Do you remember my name?",
  "rich": "He became rich after selling his company.",
  "right": "You are absolutely right.",
  "run": "I run every morning before work.",
  "sad": "She felt sad after the movie.",
  "safe": "Make sure you feel safe here.",
  "say": "What did you say?",
  "school": "My children go to school by bus.",
  "sea": "We swam in the sea all afternoon.",
  "see": "I can't see anything from here.",
  "sell": "They sell fresh fruit at the market.",
  "send": "Can you send me the file?",
  "short": "The movie was quite short.",
  "show": "Can you show me how to do this?",
  "sick": "I felt sick after lunch.",
  "sister": "My sister lives abroad.",
  "sleep": "I need more sleep.",
  "slow": "The internet is really slow today.",
  "small": "We live in a small flat.",
  "smile": "She always has a smile on her face.",
  "sometimes": "I sometimes work on weekends.",
  "song": "This is my favourite song.",
  "sorry": "I'm sorry I'm late.",
  "speak": "Do you speak English?",
  "start": "The film starts at eight.",
  "stay": "We decided to stay home tonight.",
  "still": "She still lives in Ankara.",
  "stop": "Please stop the car here.",
  "story": "Tell me a story before bed.",
  "strong": "He is very strong.",
  "student": "I was a good student at school.",
  "study": "I study every evening.",
  "sun": "The sun is shining today.",
  "sure": "Are you sure about this?",
  "talk": "Can we talk for a minute?",
  "teach": "She teaches English at a school.",
  "tell": "Can you tell me the time?",
  "thank": "Thank you for your help.",
  "think": "I think it's a good plan.",
  "time": "What time is it?",
  "tired": "I'm really tired today.",
  "today": "What are your plans for today?",
  "together": "We went to the cinema together.",
  "tomorrow": "See you tomorrow.",
  "travel": "I love to travel in summer.",
  "true": "Is this story true?",
  "try": "You should try this cake.",
  "understand": "I don't understand this question.",
  "use": "You can use my computer.",
  "very": "It's very hot today.",
  "visit": "We plan to visit my grandmother.",
  "wait": "Please wait for me here.",
  "walk": "Let's walk to the park.",
  "want": "What do you want to eat?",
  "warm": "It's warm outside today.",
  "watch": "I like to watch movies at night.",
  "water": "Can I have a glass of water?",
  "way": "This is the fastest way home.",
  "week": "I'll see you next week.",
  "well": "She sings really well.",
  "wife": "His wife works as an engineer.",
  "win": "Our team won the match.",
  "work": "I work in a small office.",
  "world": "She has travelled all over the world.",
  "write": "Can you write your name here?",
  "year": "I moved here two years ago.",
  "young": "They have two young children."
};
